name: Release on !version commit

on:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  gate:
    if: startsWith(github.event.head_commit.message, '!')
    uses: ./.github/workflows/release.yml
    secrets:
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
